name: Lint & Test

# Trigger the workflow on push or pull request commits only
on:
  push:
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: make lint
