name: Test PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: make test

      - name: Upload test coverage to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l JavaScript -r coverage/lcov.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        continue-on-error: true

      - name: Upload test coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/lcov.info
        continue-on-error: true
